# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: "masato's blog"
subtitle: ""
author: "Masato Shimizu"
email: ma6ato@gmail.com
language: en
avatar: /images/profile.png
timezone: Asia/Tokyo

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://masato.github.io/
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  auto_detect: true
  line_number: false
  tab_replace: ''
  wrap: true
  hljs: false

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
#date_format: YYYY-MM-DD
date_format: MMM D YYYY
time_format: HH:mm:ss
## Use post's date for updated date unless set in front-matter
use_date_for_updated: false

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
#theme: apollo
theme: next
#theme: landscape

# Deployment
## Docs: http://hexo.io/docs/deployment.html
## hexo-deployer-git
deploy:
  type: git
  repo: git@github.com:masato/masato.github.io.git
  branch: master

# hexo-generator-sitemap
sitemap:
  path: sitemap.xml

# hexo-generator-feed
feed:
  type: rss2
  path: rss2.xml
  limit: 20

tag_generator:
  per_page: 10

archive_generator:
  per_page: 10
  yearly: true
  monthly: true

# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 2
category: 2
tag: 2

#swiftype_key: 8GQx4kKNyyYzP_SB_GtM

algolia:
  applicationID: 'UUTBN653E1'
  apiKey: '4604ee38232a3d6b0390e8096361ad7e'
  indexName: 'Hexo'
  chunkSize: 5000
